# This is a dev docker-compose file which exports your wiki on localhost:8000
version: '3'
services:
  mediawiki:
    build: .
    volumes:
      - ./images:/images
      - ./config/run:/config
    environment:
      - URL_PREFIX=
      - DB_HOST=db
      - DB_NAME=wiki
      - DB_USER=wiki
      - DB_PASS=wiki
    ports:
      - 8087:80
    links:
      - db
    depends_on:
      - db
  db:
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_USER=wiki
      - POSTGRES_PASSWORD=wiki
