<?php
# This file was automatically generated by the MediaWiki 1.35.5
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# TODO: prefer loading config instead of config base for any settings
require_once dirname(__FILE__)."/DatabaseSettings.php";
require_once dirname(__FILE__)."/EmailSettings.php";


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = getenv("WG_SITENAME");
$wgMetaNamespace = getenv("WG_METANAMESPACE") ?: false; # If set to false, the value of $wgSitename is assumed

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv("WG_SERVER");

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];


# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en-gb";

$wgSecretKey = getenv("WG_SECRETKEY") ?: "deadbeefB16B00B5deadbeef0D15EA5EdeadbeefDEADDEADdeadbeefFFBADD11";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv("WG_UPGRADEKEY") ?: "deadbeefcafebabe";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = getenv("WG_RIGHTSPAGE") ?: ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = getenv("WG_RIGHTSURL") ?: "https://creativecommons.org/licenses/by/4.0/";
$wgRightsText = getenv("WG_RIGHTSTEXT") ?: "Creative Commons Attribution";
$wgRightsIcon = getenv("WG_RIGHTSICON") ?: "$wgResourceBasePath/resources/assets/licenses/cc-by.png";

# The following permissions were set based on your choice in the installer
#$wgGroupPermissions['*']['createaccount'] = false;
#$wgGroupPermissions['*']['edit'] = false;


# End of automatically generated settings.
# Add more configuration options below.

# TODO: prefer loading config instead of config base for any settings
require_once dirname(__FILE__)."/ContainerSettings.php";
